# Generated by Django 3.1.6 on 2021-02-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('roll_number', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('test_1', models.IntegerField(max_length=100)),
                ('test_2', models.IntegerField(max_length=100)),
                ('pre_exam_1', models.IntegerField(max_length=100)),
                ('test_3', models.IntegerField(max_length=100)),
                ('test_4', models.IntegerField(max_length=100)),
                ('pre_exam_2', models.IntegerField(max_length=100)),
            ],
        ),
    ]
