# Generated by Django 3.2.3 on 2021-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_year_subjects',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sun_name', models.CharField(max_length=30)),
            ],
        ),
    ]
