# Generated by Django 3.2.3 on 2021-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourth_year_subjects',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Second_year_subjects',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Third_year_subjects',
            fields=[
                ('sub_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='first_year_subjects',
            old_name='sun_name',
            new_name='sub_name',
        ),
    ]
