# Generated by Django 3.2.3 on 2021-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20210520_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks_detail',
            fields=[
                ('roll_number', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=10)),
                ('branch', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=30)),
                ('unit_1', models.IntegerField(max_length=30)),
                ('unit_2', models.IntegerField(max_length=30)),
                ('pre_exam_1', models.IntegerField(max_length=30)),
                ('unit_3', models.IntegerField(max_length=30)),
                ('unit_4', models.IntegerField(max_length=30)),
                ('pre_exam_2', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students_detail',
            fields=[
                ('roll_number', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='First_year_subjects',
        ),
        migrations.DeleteModel(
            name='Fourth_year_subjects',
        ),
        migrations.DeleteModel(
            name='Second_year_subjects',
        ),
        migrations.DeleteModel(
            name='Third_year_subjects',
        ),
    ]
