# Generated by Django 3.2.3 on 2021-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_auto_20210520_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('time_table_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='pre_exam_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='pre_exam_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='roll_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='unit_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='unit_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='unit_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='unit_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students_detail',
            name='roll_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
