# Generated by Django 3.2.3 on 2021-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_auto_20210521_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_detail',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks_detail',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
