# Generated by Django 3.2.3 on 2021-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marks_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('subject_name', models.CharField(max_length=30)),
                ('exam_type', models.CharField(max_length=30)),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('time_table_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
