# Generated by Django 3.2.3 on 2021-05-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks_detail',
            old_name='roll_number',
            new_name='m_roll_number',
        ),
    ]
