# Generated by Django 3.2.3 on 2021-05-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_rename_roll_number_marks_detail_m_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks_detail',
            old_name='m_roll_number',
            new_name='roll_number',
        ),
    ]
