# Generated by Django 3.2.3 on 2021-05-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_subjectlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subjectlist',
            new_name='Subject_list',
        ),
    ]
